# Generated by Django 5.1.4 on 2025-01-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoIntro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=-1),
        ),
    ]
