# Generated by Django 5.1.4 on 2025-01-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoIntro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr')], default='NA', max_length=5),
            preserve_default=False,
        ),
    ]
