# Generated by Django 5.1.4 on 2025-01-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoIntro', '0002_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
